"""remove password hash

Revision ID: 24980d54f36d
Revises: 45ac38c0befc
Create Date: 2025-03-21 11:03:35.470937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24980d54f36d'
down_revision = '45ac38c0befc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('access_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
