"""Add main_transcript_id to Transcript model

Revision ID: 3a1f9d039e1e
Revises: 3b0fe02ef7d0
Create Date: 2025-03-20 13:37:32.986935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1f9d039e1e'
down_revision = '3b0fe02ef7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_transcript_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'transcripts', ['main_transcript_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_transcript_id')

    # ### end Alembic commands ###
